Raw received JSON (time receieved 2019-09-10 17:21:38.271680): 
root        : ERROR    Unexpected error '1'
Traceback (most recent call last):
  File "./restoration_app.py", line 65, in main
    process_restoration_msg(kafka_client, msg, producer)
  File "./restoration_app.py", line 111, in process_restoration_msg
    r_json = restoration_json(restoration_json_dict)
  File "./restoration_app.py", line 171, in restoration_json
    cutmark_coord_list = cutmark_coords_dict[patho_key] # Cutmark coords to be restored to
KeyError: '1'
Raw received JSON (time receieved 2019-09-10 17:22:16.512895): 
Raw received JSON (time receieved 2019-09-10 17:23:28.716918): 
Raw received JSON (time receieved 2019-09-10 17:23:39.715452): 
root        : ERROR    Unexpected error '1'
Traceback (most recent call last):
  File "./restoration_app.py", line 65, in main

